"""Upgrade tasks

Revision ID: 2a2593a8cd19
Revises: 
Create Date: 2022-08-04 12:15:17.017326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2593a8cd19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('table_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'table_id')
    # ### end Alembic commands ###
