"""tables: name -> title

Revision ID: 30bbe3e44cad
Revises: d4f3dc12e80a
Create Date: 2022-08-09 20:49:17.040079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bbe3e44cad'
down_revision = 'd4f3dc12e80a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'name', new_column_name='title')
    # op.add_column('tables', sa.Column('title', sa.String(length=50), nullable=True))
    # op.drop_column('tables', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'title', new_column_name='name')
    # op.add_column('tables', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # op.drop_column('tables', 'title')
    # ### end Alembic commands ###
