"""add client side ids and nullable constrains

Revision ID: 627b2a8950ea
Revises: 30bbe3e44cad
Create Date: 2022-08-11 20:40:51.645622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627b2a8950ea'
down_revision = '30bbe3e44cad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('client_side_id', sa.Integer(), nullable=False))
    op.alter_column('tables', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tables', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('tasks', sa.Column('client_side_id', sa.Integer(), nullable=False))
    op.alter_column('tasks', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tasks', 'client_side_id')
    op.alter_column('tables', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tables', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tables', 'client_side_id')
    # ### end Alembic commands ###
