"""Add user mixin

Revision ID: c5cf8f16accd
Revises: 2a2593a8cd19
Create Date: 2022-08-04 15:51:26.492417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cf8f16accd'
down_revision = '2a2593a8cd19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
