"""add postition to tasks

Revision ID: d4f3dc12e80a
Revises: f0d7e76e2c15
Create Date: 2022-08-08 12:43:03.566029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f3dc12e80a'
down_revision = 'f0d7e76e2c15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'position')
    # ### end Alembic commands ###
